---
- name: GRC Lab - Setup ERPNext with Security Hardening
  hosts: all
  become: yes
  vars:
    erpnext_user: frappe
    mariadb_root_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    db_host: "{{ lookup('env', 'RDS_ENDPOINT') }}"

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3-dev
          - python3-setuptools
          - python3-pip
          - python3-venv
          - libffi-dev
          - gcc
          - libssl-dev
          - wkhtmltopdf
          - fail2ban
          - auditd
        state: present
        update_cache: yes

    - name: Create frappe user
      user:
        name: "{{ erpnext_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Install bench CLI
      pip:
        name: frappe-bench
        executable: pip3

    - name: Create bench directory
      file:
        path: "/home/{{ erpnext_user }}/erpnext"
        state: directory
        owner: "{{ erpnext_user }}"
        group: "{{ erpnext_user }}"

    - name: Initialize bench
      become_user: "{{ erpnext_user }}"
      shell: |
        cd /home/{{ erpnext_user }}/erpnext
        bench init erpnext-site --frappe-branch version-14

    - name: Create new site
      become_user: "{{ erpnext_user }}"
      shell: |
        cd /home/{{ erpnext_user }}/erpnext/erpnext-site
        bench new-site site1.local --mariadb-root-password {{ mariadb_root_password }} --admin-password admin --db-host {{ db_host }}

    - name: Get ERPNext app
      become_user: "{{ erpnext_user }}"
      shell: |
        cd /home/{{ erpnext_user }}/erpnext/erpnext-site
        bench get-app erpnext --branch version-14
        bench --site site1.local install-app erpnext

    - name: Start ERPNext
      become_user: "{{ erpnext_user }}"
      shell: |
        cd /home/{{ erpnext_user }}/erpnext/erpnext-site
        bench start &

    - name: Enable auditd service
      systemd:
        name: auditd
        state: started
        enabled: yes

    - name: Enable fail2ban service
      systemd:
        name: fail2ban
        state: started
        enabled: yes
